updated from MCM to IAF

diff --git a/terraform/iaf/Makefile b/terraform/iaf/Makefile
--- a/terraform/iaf/Makefile
+++ b/terraform/iaf/Makefile
@@ -9,23 +9,14 @@ var-tf:
 
 define test-namespace
 	@if kubectl get namespace $(1) --kubeconfig=$(2) > /dev/null; \
-		then $(ECHO) "$(P) $(PASS) CP4MCM Namespace Exists";\
-		else $(ECHO) "$(P) $(FAIL) CP4MCM Namespace not found"; exit 1; \
-	fi
-endef
-
-define test-endpoint
-	@if [[ -n $(1) ]]; \
-		then $(ECHO) "$(P) $(PASS) CP4MCM Running"; \
-		else $(ECHO) "$(P) $(FAIL) CP4MCM is not Running. Endpoint not found"; exit 1; \
+		then $(ECHO) "$(P) $(PASS) IAF Namespace Exists";\
+		else $(ECHO) "$(P) $(FAIL) IAF Namespace not found"; exit 1; \
 	fi
 endef
 
 test-tf:
-	$(call test-namespace,$$(terraform output cp4mcm_namespace),$$(terraform output kubeconfig))
-	$(call test-endpoint,$$(terraform output cp4mcm_endpoint))
+	$(call test-namespace,$$(terraform output iaf_namespace),$$(terraform output kubeconfig))
 
 test-sch:
 	@[[ -e $(WORKSPACE_OUTPUT_FILE) ]]
-	$(call test-namespace,$$(cat $(WORKSPACE_OUTPUT_FILE) | jq -r '.[].output_values[].cp4mcm_namespace.value'),$$(cat $(WORKSPACE_OUTPUT_FILE) | jq -r '.[].output_values[].kubeconfig.value'))
-	$(call test-endpoint,$$(cat $(WORKSPACE_OUTPUT_FILE) | jq -r '.[].output_values[].cp4mcm_endpoint.value'))
+	$(call test-namespace,$$(cat $(WORKSPACE_OUTPUT_FILE) | jq -r '.[].output_values[].iaf_namespace.value'),$$(cat $(WORKSPACE_OUTPUT_FILE) | jq -r '.[].output_values[].kubeconfig.value'))
